dist: xenial
language: python
python:
  - "3.7"
before_install:
  - sudo apt-get install -y firejail git 
# command to install dependencies
install:
  - pip install .
# command to run tests
script:
  - pytest
