FROM python:3.14-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends git ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /code
COPY . .

RUN pip3 install --no-cache-dir ".[web]"

EXPOSE 8001

CMD ["gunicorn", "--bind", ":8001", "--workers", "3", "athina_web.wsgi:application"]
