# Generated by Django 2.0.4 on 2018-04-04 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DirectoryFiles',
            new_name='Directory',
        ),
    ]
