# Generated by Django 2.0.4 on 2018-04-04 20:49

import datetime
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_auto_20180404_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 4, 20, 49, 53, 420899, tzinfo=timezone.utc), verbose_name='Date Created'),
        ),
    ]
