# Generated by Django 2.0.4 on 2018-04-04 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_directory_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created'),
        ),
    ]
