# Generated by Django 2.0.4 on 2018-04-04 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_auto_20180404_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('absolute_path', models.CharField(max_length=200)),
                ('owner', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
            ],
        ),
        migrations.DeleteModel(
            name='Directory',
        ),
    ]
