# Generated by Django 2.0.4 on 2018-04-04 23:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0006_auto_20180404_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date Created'),
        ),
    ]
