# Generated by Django 2.0.4 on 2018-04-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0007_auto_20180404_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='owner',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
