# Generated by Django 2.0.4 on 2018-04-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0011_auto_20180406_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='status',
            new_name='active',
        ),
        migrations.AddField(
            model_name='assignment',
            name='simulate',
            field=models.BooleanField(default=True),
        ),
    ]
