# Generated by Django 2.0.4 on 2019-03-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0013_auto_20180419_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='git_password',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='assignment',
            name='git_source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='assignment',
            name='git_username',
            field=models.CharField(default='', max_length=255),
        ),
    ]
