# Generated by Django 2.0.4 on 2019-03-07 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0014_auto_20190307_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='git_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='git_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
