# Generated by Django 3.2.25 on 2026-09-02 00:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0017_auto_20190327_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('owner', models.IntegerField(default=1, editable=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date Created')),
            ],
            options={
                'verbose_name_plural': 'courses',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='assignments.course'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255)),
                ('username', models.CharField(blank=True, help_text='Derived from email prefix if left blank.', max_length=255)),
                ('gitlab_username', models.CharField(blank=True, default='', max_length=255)),
                ('repository_url', models.CharField(blank=True, default='', max_length=500)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Date Added')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='assignments.course')),
            ],
            options={
                'ordering': ['email'],
                'unique_together': {('course', 'email')},
            },
        ),
    ]
