# Generated by Django 3.2.25 on 2026-09-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0018_auto_20260902_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'owner')},
        ),
    ]
