# Generated by Django 5.2.8 on 2026-09-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0019_auto_20260902_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='gitlab_project_id',
            field=models.PositiveIntegerField(default=0, help_text="Numeric GitLab project ID. Find it in your GitLab project's Settings > General."),
        ),
        migrations.AddField(
            model_name='assignment',
            name='output_method',
            field=models.CharField(choices=[('canvas', 'Canvas LMS'), ('gitlab_issues', 'GitLab Issues')], default='canvas', max_length=20),
        ),
    ]
