# Generated by Django 5.2.8 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0020_assignment_gitlab_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='notified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Notified At'),
        ),
    ]
