# Generated by Django 3.2.25 on 2026-09-02 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='github_enabled',
            field=models.BooleanField(default=False, help_text='Activate GitHub integration.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_token',
            field=models.CharField(blank=True, default='', help_text='Personal access token.', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_url',
            field=models.CharField(blank=True, default='github.com', help_text='GitHub instance URL (e.g. github.com).', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='github_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gitlab_enabled',
            field=models.BooleanField(default=False, help_text='Activate GitLab integration.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gitlab_token',
            field=models.CharField(blank=True, default='', help_text='Personal access token.', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gitlab_url',
            field=models.CharField(blank=True, default='gitlab.com', help_text='GitLab instance URL (e.g. gitlab.com or git.myuni.edu).', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gitlab_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='git_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='git_username',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
