# Generated by Django 3.2.25 on 2026-09-02 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20260902_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='github_url',
        ),
    ]
