# Generated by Django 3.2.25 on 2026-09-02 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_remove_userprofile_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='managed_by',
            field=models.ManyToManyField(blank=True, help_text='Faculty members this TA assists (for TAs only).', related_name='ta_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty'), ('ta', 'Teaching Assistant')], default='faculty', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='github_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gitlab_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gitlab_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gitlab_url',
            field=models.CharField(blank=True, default='gitlab.com', max_length=255),
        ),
    ]
