# Generated by Django 3.2.25 on 2026-09-03 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20260902_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='llm_api_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='llm_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='llm_endpoint_url',
            field=models.CharField(blank=True, default='https://api.openai.com/v1', help_text='OpenAI-compatible endpoint URL', max_length=512),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='llm_model',
            field=models.CharField(blank=True, default='gpt-4o-mini', help_text='Model name, e.g. gpt-4o-mini, gpt-4o, claude-3-haiku', max_length=128),
        ),
    ]
