# Generated by Django 5.2 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20260903_0320'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notify_api_key',
            field=models.BooleanField(default=False, help_text='Send email notification with API key when a student repo is created'),
        ),
    ]
