# Generated by Django 5.2 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_notify_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notify_api_key',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_students',
            field=models.BooleanField(default=False, help_text='Send email notification to students when their repository is created'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_api_key',
            field=models.CharField(blank=True, default='', help_text='API key for the email notification service (e.g. SendGrid, Mailgun)', max_length=512),
        ),
    ]
