# Generated by Django 5.2 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_replace_notify_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notification_api_key',
            field=models.CharField(blank=True, default='', help_text='Resend API key (re_...) used to send student notifications', max_length=512),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_from_email',
            field=models.CharField(blank=True, default='', help_text="Verified sender address for Resend, e.g. 'Athina <noreply@yourdomain.edu>'. Leave blank to use Resend's sandbox sender.", max_length=255),
        ),
    ]
