# Generated by Django 5.2.8 on 2026-09-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_repair_ta_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_reply_to',
            field=models.CharField(blank=True, default='', help_text="Optional reply-to address, e.g. 'Instructor <you@university.edu>'. Student replies will go here instead of to the from address. The address does not need to be verified in Resend.", max_length=255),
        ),
    ]
